/*
DROP TABLE "CANCHA" cascade constraints;
DROP TABLE "CATEGORIA" cascade constraints;
DROP TABLE "COMUNA" cascade constraints;
DROP TABLE "EQUIPO" cascade constraints;
DROP TABLE "EVENTO" cascade constraints;
DROP TABLE "JUGADOR" cascade constraints;
DROP TABLE "JUGADOR_EQUIPO" cascade constraints;
DROP TABLE "PARTIDO" cascade constraints;
DROP TABLE "PROGRAMACION" cascade constraints;
DROP TABLE "TARIFA" cascade constraints;
DROP TABLE "TIPO_EVENTO" cascade constraints;
DROP TABLE "USUARIO" cascade constraints;
*/
--------------------------------------------------------
-- Archivo creado  - sábado-septiembre-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CANCHA
--------------------------------------------------------

  CREATE TABLE "CANCHA" ("ID_CANCHA" NUMBER, "NOMBRE" VARCHAR2(50)) ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "CATEGORIA" ("ID_CATEGORIA" NUMBER(*,0), "NOMBRE" VARCHAR2(50), "EDAD_MINIMA" NUMBER(*,0), "EDAD_MAXIMO" NUMBER(*,0)) ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "COMUNA" ("NOMBRE" VARCHAR2(100), "ID" NUMBER) ;
--------------------------------------------------------
--  DDL for Table EQUIPO
--------------------------------------------------------

  CREATE TABLE "EQUIPO" ("ID_EQUIPO" NUMBER(*,0), "NOMBRE" VARCHAR2(50), "CANTIDAD_JUGADOR" NUMBER(*,0), "FECHA_CREACION" DATE, "ID_CATEGORIA" NUMBER(*,0)) ;
--------------------------------------------------------
--  DDL for Table EVENTO
--------------------------------------------------------

  CREATE TABLE "EVENTO" ("ID_EVENTO" NUMBER, "ID_PARTIDO" NUMBER, "RUT_JUGADOR" NUMBER, "MINUTO" NUMBER(3,0), "EQUIPO_LOCAL" VARCHAR2(50), "EQUIPO_VISITA" VARCHAR2(50), "EQUIPO_JUGADOR" VARCHAR2(50), "ID_TIPO_EVENTO" VARCHAR2(2), "FECHA" DATE, "NOMBRE_JUGADOR" VARCHAR2(50), "APELLIDO_JUGADOR" VARCHAR2(50), "CAMISETA" NUMBER(3,0)) ;
--------------------------------------------------------
--  DDL for Table JUGADOR
--------------------------------------------------------

  CREATE TABLE "JUGADOR" ("RUT" NUMBER(8,0), "DV" CHAR(1), "NOMBRE" VARCHAR2(50), "APELLIDO" VARCHAR2(50)) ;
--------------------------------------------------------
--  DDL for Table JUGADOR_EQUIPO
--------------------------------------------------------

  CREATE TABLE "JUGADOR_EQUIPO" ("ID_JUGADOR_EQUIPO" NUMBER(*,0), "FECHA_INCORPORACION" DATE, "CAMISETA" VARCHAR2(3), "ID_EQUIPO" NUMBER(*,0), "RUT_JUGADOR" NUMBER(*,0)) ;
--------------------------------------------------------
--  DDL for Table PARTIDO
--------------------------------------------------------

  CREATE TABLE "PARTIDO" ("ID_PARTIDO" NUMBER(*,0), "ID_PROGRAMACION" NUMBER(*,0), "INICIO" TIMESTAMP (6), "FIN" TIMESTAMP (6), "GOLES_LOCAL" NUMBER(2,0), "GOLES_VISITA" NUMBER(2,0), "ID_EQUIPO_LOCAL" NUMBER(*,0), "ID_EQUIPO_VISITA" NUMBER(*,0), "ID_USER" NUMBER, "ID_CANCHA" NUMBER, "FECHA" DATE, "EQUIPO_LOCAL" VARCHAR2(50), "EQUIPO_VISITA" VARCHAR2(50), "CANCHA" VARCHAR2(50), "ID_TARIFA" NUMBER DEFAULT 1) ;
--------------------------------------------------------
--  DDL for Table PROGRAMACION
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION" ("ID_PROGRAMACION" NUMBER, "ID_EQUIPO_1" NUMBER, "ID_EQUIPO_2" NUMBER, "FECHA" DATE, "HORA" TIMESTAMP (6), "ID_TARIFA" NUMBER, "VALOR_PAGADO" NUMBER(7,0) DEFAULT 0, "ESTADO" CHAR(2) DEFAULT 'NJ', "EQUIPO_1" VARCHAR2(50), "EQUIPO_2" VARCHAR2(50), "MINUTOS_JUGADOS" NUMBER) ;
--------------------------------------------------------
--  DDL for Table TARIFA
--------------------------------------------------------

  CREATE TABLE "TARIFA" ("ID_TARIFA" NUMBER, "DESCRIPCION" VARCHAR2(50), "VALOR" NUMBER, "FECHA_CREACION" DATE, "FECHA_ACTUALIZACION" DATE, "FECHA_ELIMINACION" DATE, "ID_USER_CREACION" NUMBER, "ID_USER_ACTUALIZACION" NUMBER, "ID_USER_ELIMINACION" NUMBER) ;
--------------------------------------------------------
--  DDL for Table TIPO_EVENTO
--------------------------------------------------------

  CREATE TABLE "TIPO_EVENTO" ("DESCRIPCION" VARCHAR2(30), "RELEVANTE" CHAR(1) DEFAULT 'N', "ID_TIPO_EVENTO" VARCHAR2(2)) ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "USUARIO" ("ID_USER" NUMBER(*,0), "USERNAME" VARCHAR2(50), "PASSWORD" VARCHAR2(50), "FECHA_CREACION" DATE, "FECHA_BLOQUEO" DATE, "NOMBRE" VARCHAR2(50), "APELLIDO" VARCHAR2(50)) ;
REM INSERTING into CANCHA
SET DEFINE OFF;
Insert into CANCHA (ID_CANCHA,NOMBRE) values ('1','NAPOLES');
Insert into CANCHA (ID_CANCHA,NOMBRE) values ('2','MILAN');
Insert into CANCHA (ID_CANCHA,NOMBRE) values ('3','MESSINA');
Insert into CANCHA (ID_CANCHA,NOMBRE) values ('4','ROMA');
Insert into CANCHA (ID_CANCHA,NOMBRE) values ('5','LIVORNO');
Insert into CANCHA (ID_CANCHA,NOMBRE) values ('6','VENECIA');
Insert into CANCHA (ID_CANCHA,NOMBRE) values ('7','TURIN');
Insert into CANCHA (ID_CANCHA,NOMBRE) values ('8','FLORENCIA');
REM INSERTING into CATEGORIA
SET DEFINE OFF;
Insert into CATEGORIA (ID_CATEGORIA,NOMBRE,EDAD_MINIMA,EDAD_MAXIMO) values ('2','PROFESIONAL','18','40');
Insert into CATEGORIA (ID_CATEGORIA,NOMBRE,EDAD_MINIMA,EDAD_MAXIMO) values ('3','EMPRESA','18','55');
Insert into CATEGORIA (ID_CATEGORIA,NOMBRE,EDAD_MINIMA,EDAD_MAXIMO) values ('4','JUNIOR','8','13');
Insert into CATEGORIA (ID_CATEGORIA,NOMBRE,EDAD_MINIMA,EDAD_MAXIMO) values ('1','AMATEUR','14','17');
REM INSERTING into COMUNA
SET DEFINE OFF;
Insert into COMUNA (NOMBRE,ID) values ('Santiago','1');
Insert into COMUNA (NOMBRE,ID) values ('Cerrillos','2');
Insert into COMUNA (NOMBRE,ID) values ('Cerro Navia','3');
Insert into COMUNA (NOMBRE,ID) values ('Puente Alto','4');
Insert into COMUNA (NOMBRE,ID) values ('Pirque','5');
Insert into COMUNA (NOMBRE,ID) values ('Conchalí','6');
Insert into COMUNA (NOMBRE,ID) values ('El Bosque','7');
Insert into COMUNA (NOMBRE,ID) values ('Estación Central','8');
Insert into COMUNA (NOMBRE,ID) values ('Huechuraba','9');
Insert into COMUNA (NOMBRE,ID) values ('Independencia','10');
Insert into COMUNA (NOMBRE,ID) values ('La Cisterna','11');
Insert into COMUNA (NOMBRE,ID) values ('La Florida','12');
Insert into COMUNA (NOMBRE,ID) values ('La Granja','13');
Insert into COMUNA (NOMBRE,ID) values ('La Pintana','14');
Insert into COMUNA (NOMBRE,ID) values ('La Reina','15');
Insert into COMUNA (NOMBRE,ID) values ('Las Condes','16');
Insert into COMUNA (NOMBRE,ID) values ('Lo Barnechea','17');
Insert into COMUNA (NOMBRE,ID) values ('Lo Espejo','18');
Insert into COMUNA (NOMBRE,ID) values ('Lo Prado','19');
Insert into COMUNA (NOMBRE,ID) values ('Macul','20');
Insert into COMUNA (NOMBRE,ID) values ('Maipú','21');
Insert into COMUNA (NOMBRE,ID) values ('Ñuñoa','22');
Insert into COMUNA (NOMBRE,ID) values ('Pedro Aguirre Cerda','23');
Insert into COMUNA (NOMBRE,ID) values ('Peñalolén','24');
Insert into COMUNA (NOMBRE,ID) values ('Providencia','25');
Insert into COMUNA (NOMBRE,ID) values ('Pudahuel','26');
Insert into COMUNA (NOMBRE,ID) values ('Quilicura','27');
Insert into COMUNA (NOMBRE,ID) values ('Quinta Normal','28');
Insert into COMUNA (NOMBRE,ID) values ('Recoleta','29');
Insert into COMUNA (NOMBRE,ID) values ('Renca','30');
Insert into COMUNA (NOMBRE,ID) values ('San Joaquín','31');
Insert into COMUNA (NOMBRE,ID) values ('San Miguel','32');
Insert into COMUNA (NOMBRE,ID) values ('San Ramón','33');
Insert into COMUNA (NOMBRE,ID) values ('Vitacura','34');
Insert into COMUNA (NOMBRE,ID) values ('San José de Maipo','35');
Insert into COMUNA (NOMBRE,ID) values ('Colina','36');
Insert into COMUNA (NOMBRE,ID) values ('Lampa','37');
Insert into COMUNA (NOMBRE,ID) values ('Tiltil','38');
Insert into COMUNA (NOMBRE,ID) values ('San Bernardo','39');
Insert into COMUNA (NOMBRE,ID) values ('Buin','40');
Insert into COMUNA (NOMBRE,ID) values ('Calera de Tango','41');
Insert into COMUNA (NOMBRE,ID) values ('Paine','42');
Insert into COMUNA (NOMBRE,ID) values ('Melipilla','43');
Insert into COMUNA (NOMBRE,ID) values ('Alhué','44');
Insert into COMUNA (NOMBRE,ID) values ('Curacaví','45');
Insert into COMUNA (NOMBRE,ID) values ('María Pinto','46');
Insert into COMUNA (NOMBRE,ID) values ('San Pedro','47');
Insert into COMUNA (NOMBRE,ID) values ('Talagante','48');
Insert into COMUNA (NOMBRE,ID) values ('El Monte','49');
Insert into COMUNA (NOMBRE,ID) values ('Isla de Maipo','50');
Insert into COMUNA (NOMBRE,ID) values ('Padre Hurtado','51');
Insert into COMUNA (NOMBRE,ID) values ('Peñaflor','52');
REM INSERTING into EQUIPO
SET DEFINE OFF;
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('3','TELETUBBIES','8',to_date('14/11/17','DD/MM/RR'),'4');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('4','CACHORROS','8',to_date('14/11/17','DD/MM/RR'),'4');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('5','DEVASTADORES','9',to_date('12/01/18','DD/MM/RR'),'1');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('6','DON JUAN FC','9',to_date('13/06/18','DD/MM/RR'),'1');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('7','STOLICHVAYA','9',to_date('01/01/18','DD/MM/RR'),'1');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('8','OLIMPIA','9',to_date('06/02/18','DD/MM/RR'),'1');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('9','LOGISTICA','9',to_date('02/06/18','DD/MM/RR'),'3');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('10','BODEGA','9',to_date('02/06/18','DD/MM/RR'),'3');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('11','CONTABILIDAD','9',to_date('02/06/18','DD/MM/RR'),'3');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('12','INFORMATICA','9',to_date('02/06/18','DD/MM/RR'),'3');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('1','GRINGUITOS','8',to_date('14/11/17','DD/MM/RR'),'4');
Insert into EQUIPO (ID_EQUIPO,NOMBRE,CANTIDAD_JUGADOR,FECHA_CREACION,ID_CATEGORIA) values ('2','PINGUINOS','8',to_date('14/11/17','DD/MM/RR'),'4');
REM INSERTING into EVENTO
SET DEFINE OFF;
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('1','1','8801699','89','TELETUBBIES','CACHORROS','TELETUBBIES','GL',to_date('15/08/18','DD/MM/RR'),'ERIK','ARAYA ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('2','1','8801699','68','TELETUBBIES','CACHORROS','TELETUBBIES','GL',to_date('15/08/18','DD/MM/RR'),'ERIK','ARAYA ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('3','1','8801699','54','TELETUBBIES','CACHORROS','TELETUBBIES','GL',to_date('15/08/18','DD/MM/RR'),'ERIK','ARAYA ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('4','1','12141116','80','TELETUBBIES','CACHORROS','CACHORROS','GL',to_date('15/08/18','DD/MM/RR'),'CRISTIAN','CRUZ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('5','2','1669343','45','GRINGUITOS','PINGUINOS','GRINGUITOS','GL',to_date('15/08/18','DD/MM/RR'),'WALTER RAUL ','PEREZ ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('6','2','1669343','54','GRINGUITOS','PINGUINOS','GRINGUITOS','GL',to_date('15/08/18','DD/MM/RR'),'WALTER RAUL ','PEREZ ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('7','5','38647112','5','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE RENE','ZAPATA','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('8','5','38647112','74','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE RENE','ZAPATA','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('9','5','38647112','79','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE RENE','ZAPATA','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('10','5','38647112','22','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE RENE','ZAPATA','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('11','5','38647112','36','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE RENE','ZAPATA','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('12','5','47072543','79','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/RR'),'CAMILO','CARVACHO','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('13','5','47072543','76','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/RR'),'CAMILO','CARVACHO','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('14','5','47072543','78','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/RR'),'CAMILO','CARVACHO','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('15','5','47072543','25','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/RR'),'CAMILO','CARVACHO','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('16','5','47072543','67','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/RR'),'CAMILO','CARVACHO','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('17','5','47072543','80','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/RR'),'CAMILO','CARVACHO','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('18','5','47072543','93','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/RR'),'CAMILO','CARVACHO','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('19','6','58950320','62','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE ','FUENTES ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('20','6','58950320','38','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE ','FUENTES ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('21','6','58950320','5','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE ','FUENTES ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('22','6','58950320','19','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE ','FUENTES ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('23','6','58950320','75','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/RR'),'JOSE ','FUENTES ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('24','6','54036880','53','INFORMATICA','CONTABILIDAD','CONTABILIDAD','GL',to_date('17/08/18','DD/MM/RR'),'FRANCESCO','MATHEU','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('25','6','54036880','46','INFORMATICA','CONTABILIDAD','CONTABILIDAD','GL',to_date('17/08/18','DD/MM/RR'),'FRANCESCO','MATHEU','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('26','6','54036880','49','INFORMATICA','CONTABILIDAD','CONTABILIDAD','GL',to_date('17/08/18','DD/MM/RR'),'FRANCESCO','MATHEU','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('27','6','54036880','66','INFORMATICA','CONTABILIDAD','CONTABILIDAD','GL',to_date('17/08/18','DD/MM/RR'),'FRANCESCO','MATHEU','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('28','9','20322516','7','DON JUAN FC','DEVASTADORES','DEVASTADORES','GL',to_date('19/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('29','10','37158020','75','STOLICHVAYA','OLIMPIA','OLIMPIA','GL',to_date('19/08/18','DD/MM/RR'),'PATRICIO','MARIN','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('30','11','38647112','39','BODEGA','LOGISTICA','LOGISTICA','GL',to_date('19/08/18','DD/MM/RR'),'JOSE RENE','ZAPATA','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('31','11','38647112','33','BODEGA','LOGISTICA','LOGISTICA','GL',to_date('19/08/18','DD/MM/RR'),'JOSE RENE','ZAPATA','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('32','14','12141116','32','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/RR'),'CRISTIAN','CRUZ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('33','14','12141116','92','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/RR'),'CRISTIAN','CRUZ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('34','14','12141116','44','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/RR'),'CRISTIAN','CRUZ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('35','14','12141116','87','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/RR'),'CRISTIAN','CRUZ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('36','14','12141116','80','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/RR'),'CRISTIAN','CRUZ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('37','14','12141116','2','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/RR'),'CRISTIAN','CRUZ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('38','14','12141116','93','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/RR'),'CRISTIAN','CRUZ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('39','14','1669343','74','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/RR'),'WALTER RAUL ','PEREZ ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('40','14','1669343','47','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/RR'),'WALTER RAUL ','PEREZ ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('41','14','1669343','78','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/RR'),'WALTER RAUL ','PEREZ ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('42','14','1669343','53','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/RR'),'WALTER RAUL ','PEREZ ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('43','14','1669343','21','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/RR'),'WALTER RAUL ','PEREZ ','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('44','15','29585336','63','STOLICHVAYA','DEVASTADORES','STOLICHVAYA','GL',to_date('20/08/18','DD/MM/RR'),'GUIDO','FARIAS','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('45','15','29585336','60','STOLICHVAYA','DEVASTADORES','STOLICHVAYA','GL',to_date('20/08/18','DD/MM/RR'),'GUIDO','FARIAS','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('46','15','20322516','88','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('47','15','20322516','59','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('48','15','20322516','43','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('49','15','20322516','73','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('50','15','20322516','12','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('51','15','20322516','25','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('52','16','23061531','81','DON JUAN FC','OLIMPIA','DON JUAN FC','GL',to_date('21/08/18','DD/MM/RR'),'DAVID','CANCINO','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('53','16','23061531','23','DON JUAN FC','OLIMPIA','DON JUAN FC','GL',to_date('21/08/18','DD/MM/RR'),'DAVID','CANCINO','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('54','16','23061531','93','DON JUAN FC','OLIMPIA','DON JUAN FC','GL',to_date('21/08/18','DD/MM/RR'),'DAVID','CANCINO','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('55','16','37158020','23','DON JUAN FC','OLIMPIA','OLIMPIA','GL',to_date('21/08/18','DD/MM/RR'),'PATRICIO','MARIN','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('56','17','38647112','40','CONTABILIDAD','LOGISTICA','LOGISTICA','GL',to_date('21/08/18','DD/MM/RR'),'JOSE RENE','ZAPATA','10');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('57','20','54036880','22','CONTABILIDAD','CACHORROS','CONTABILIDAD','GL',to_date('23/08/18','DD/MM/RR'),'FRANCESCO','MATHEU','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('58','21','37158020','25','OLIMPIA','DEVASTADORES','OLIMPIA','GL',to_date('23/08/18','DD/MM/RR'),'PATRICIO','MARIN','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('59','21','37158020','86','OLIMPIA','DEVASTADORES','OLIMPIA','GL',to_date('23/08/18','DD/MM/RR'),'PATRICIO','MARIN','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('60','21','20322516','26','OLIMPIA','DEVASTADORES','DEVASTADORES','GL',to_date('23/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('61','26','37158020','92','CONTABILIDAD','OLIMPIA','OLIMPIA','GL',to_date('26/08/18','DD/MM/RR'),'PATRICIO','MARIN','11');
Insert into EVENTO (ID_EVENTO,ID_PARTIDO,RUT_JUGADOR,MINUTO,EQUIPO_LOCAL,EQUIPO_VISITA,EQUIPO_JUGADOR,ID_TIPO_EVENTO,FECHA,NOMBRE_JUGADOR,APELLIDO_JUGADOR,CAMISETA) values ('62','27','20322516','38','BODEGA','DEVASTADORES','DEVASTADORES','GL',to_date('27/08/18','DD/MM/RR'),'DANIEL LEOPOLDO','DIAZ','9');
REM INSERTING into JUGADOR
SET DEFINE OFF;
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('98326882','K','Hilel','VIDAL');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('24809221','1','Zeph','CORVAL�?N');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('71629611','3','Gannon','RUIZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('87602978','2','Neville','VILLAGÓMEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('59166208','2','Marvin','ROJAS ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('23061531','4','Samson','CANCINO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('2194920','5','Tyler','ORLANDO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('52536075','K','Neville','CORTES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('5281817','6','Adam','GUERRERO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('76762745','9','Fitzgerald','AGUIRRE ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('25405449','6','Kasimir','VALDES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('53074745','K','Sawyer','MORALES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('61935771','K','Dante','RUIZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('56848279','4','Tate','GUITAL');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('95435955','7','Berk','FUENZALIDA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('17166549','3','Colt','SALAS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('21898020','1','Colton','MELENDES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('64226636','5','Kamal','HUENCHULAO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('59088863','K','Declan','ALVAREZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('84735838','6','Magee','ROKY');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('3018117','4','Plato','JURICIC');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('17255206','4','Carlos','SANDOVAL');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('68461289','1','Ray','VASQUEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('87069852','6','Callum','UGEL');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('74411676','7','Abdul','SOTO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('1394262','5','Derek','ASTUDILLO ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('53223034','9','Zahir','TOLOZA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('55007800','7','Marshall','MORA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('35098122','5','Forrest','CORVAL�?N');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('29965487','7','Melvin','SANDROCK');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('31588155','2','Alexander','TAPIA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('28143035','1','Berk','PIZARRO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('31421030','1','Herrod','GRUSIC');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('81621802','0','Hammett','VALENZUELA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('24498120','8','Barry','MUÑOZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('95706709','3','Driscoll','PRIETO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('8676153','K','Elvis','GONZALEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('4448142','1','Nathan','RIFO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('56816611','6','Dorian','ITURRIAGA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('40928167','2','Rahim','GARETTO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('87859171','2','Hamilton','ALLENDE ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('95649644','6','Vance','MORA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('69360054','5','Barclay','ROJAS ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('71291573','0','Ahmed','MARIN');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('3438218','2','Nissim','BURGOS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('98704176','5','Jamal','MATUS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('69107184','7','Vincent','LEON');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('52307509','8','Oliver','GOMEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('80224656','0','Joseph','AGUILERA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('37196455','K','Gil','CORTES ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('87411834','6','Keegan','CASTRO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('38463171','1','Bevis','CASTRO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('75528696','6','Driscoll','ALLENDES ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('37158020','4','Silas','MARIN');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('34821345','8','Galvin','ACEVEDO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('29769217','8','Ivan','MORENO ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('9539267','9','Kyle','PEREZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('52251926','K','Micah','REBELLAUT');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('1512379','6','Clark','CASTILLO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('45577349','0','Oren','MAZO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('14051531','0','Hunter','CANTILLANA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('43047268','2','Hamish','CASTILLANA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('60810081','4','Nehru','FREIRE');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('19612878','6','Austin','OPAZO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('77744173','6','Asher','EBENSPERGER');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('39476444','2','Kato','GUTIERREZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('9679940','3','Thane','OPAZO ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('66939180','3','Alec','OPAZO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('97131457','5','Kibo','TOLOSA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('7901645','4','Lars','VILLARROEL');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('41906482','3','Roth','VALDERRAMA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('83705190','8','Adam','CARVACHO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('47072543','5','Keane','CARVACHO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('88678790','1','Arden','JARAMILLO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('78864381','0','Travis','RIOS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('95935409','K','August','ALVAREZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('60647857','7','Vernon','SOTOMAYOR');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('30817381','K','Hunter','BARBAZZO ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('10038488','4','Philip','BUSTAMANTE');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('62971708','0','Louis','FARFAN');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('37734232','1','Ciaran','ELGUETA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('80153372','8','Flynn','ALEGRIA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('62584238','7','Salvador','MORAGA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('3539534','2','Hedley','MATHEU');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('74632336','0','Wang','VIDAL');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('54036880','5','Jerome','MATHEU');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('1669343','K','Nash','PEREZ ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('73358089','5','Dexter','VELASQUEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('79196815','1','Rogan','VERA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('29425171','5','Mannix','LANDMAN');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('12141116','4','Oren','CRUZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('82532139','K','Lamar','VELASQUEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('87505402','3','Kermit','MARDONES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('80481373','K','August','MERCADO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('2040747','6','Walter','MEND');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('47269316','6','Gavin','MENDOZA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('20500351','7','Paki','BUSTOS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('20254800','8','Calvin','RAMIREZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('29585336','0','Lars','FARIAS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('535669','5','Andrew','CAPURRO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('27570413','K','Dolan','PAVEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('90108466','1','Gil','CASTRO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('49464632','3','Brett','CAÑAS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('5845793','0','Colin','DIOCARES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('38647112','6','Hiram','ZAPATA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('75432051','6','Arden','CASTILLO ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('95844772','8','Jonas','PINTO ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('22968901','0','Cooper','GUTIERREZ ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('67487285','2','Darius','BOIZARD');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('33209034','8','Erich','DE SOLMINIHAC ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('8299751','2','Thomas','VIZCARRA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('52790811','6','Benjamin','JELDRES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('93491939','4','Victor','COSTA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('69186761','7','Honorato','RAMIREZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('80194418','3','Lewis','MARQUEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('45427375','3','Stuart','YAÑEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('20322516','4','Bert','DIAZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('5289556','1','Colorado','OLMEDO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('38370020','5','Kevin','IBARRA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('57189858','6','Murphy','RODRIGUEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('30213987','3','Honorato','RODRIGUEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('22345651','0','Ezekiel','PONTIGO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('7583193','5','Rudyard','ROZAS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('21364643','5','Erasmus','ARACENA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('81241666','9','Wade','ESTEVES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('86403645','7','Ryder','MORA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('52024078','0','Reed','CABELLO ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('94868574','4','Rogan','CASTELLANOS ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('82896932','3','Quentin','GONZALEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('58950320','1','Dennis','FUENTES ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('5586435','7','Garrison','TENRROZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('92806065','9','Laith','SALAZAR');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('58232331','3','Arden','REYES');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('17665094','K','Phelan','SALAS ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('60276134','7','Marshall','VILLAGRA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('33266578','2','Alvin','MORALES ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('12987266','7','Tyrone','ARANCIBIA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('54806654','9','Lucius','NIEDERMAYR');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('15905690','2','Wallace','PEREZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('19768693','6','Xanthus','CABEZAS');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('28297306','5','Chancellor','MARTINEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('9002811','1','Isaiah','SEPULVEDA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('78614529','5','Nigel','FERNANDEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('93839085','1','Barclay','YAÑEZ ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('25536358','1','Wang','NARVAEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('79169157','5','Upton','VERA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('98949453','8','Lester','CHAVEZ ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('24472749','2','Abdul','ARANGUIZ ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('95774105','3','Hop','GONZALEZ ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('44653774','1','Aladdin','GONZALEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('8801699','8','Rafael','ARAYA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('46944450','3','Kaseem','PIZARRO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('11879295','5','Holmes','PACHECO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('82409872','7','Jonah','MANCILLA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('93613285','5','Melvin','MORENO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('67777880','6','Kennedy','PASTENE');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('15659921','2','Austin','SEVILLA');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('52592973','6','Lane','SEVILLA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('61825827','0','Donovan','LANDABUR');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('27961478','K','Stuart','DE LA HARPE ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('72765170','5','Beck','HERMOSILLA ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('87626168','5','Kaseem','BELTRAN ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('94746634','8','Hop','COX');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('47221583','3','Jonah','VIDAL ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('95046566','2','Abdul','ESPEJO');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('88078561','3','Hop','MENDEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('58597347','5','Kennedy','MARTINEZ');
Insert into JUGADOR (RUT,DV,NOMBRE,APELLIDO) values ('47551798','9','Rafael','GATICA');
REM INSERTING into JUGADOR_EQUIPO
SET DEFINE OFF;
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('1',to_date('20/07/18','DD/MM/RR'),'1','1','535669');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('2',to_date('20/07/18','DD/MM/RR'),'2','1','1394262');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('3',to_date('20/07/18','DD/MM/RR'),'3','1','1512379');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('4',to_date('20/07/18','DD/MM/RR'),'11','1','1669343');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('5',to_date('20/07/18','DD/MM/RR'),'7','1','2040747');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('6',to_date('20/07/18','DD/MM/RR'),'8','1','2194920');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('7',to_date('20/07/18','DD/MM/RR'),'5','1','3018117');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('8',to_date('20/07/18','DD/MM/RR'),'9','1','3438218');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('9',to_date('20/07/18','DD/MM/RR'),'10','2','3539534');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('10',to_date('20/07/18','DD/MM/RR'),'5','2','4448142');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('11',to_date('20/07/18','DD/MM/RR'),'7','2','5281817');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('12',to_date('20/07/18','DD/MM/RR'),'1','2','5289556');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('13',to_date('20/07/18','DD/MM/RR'),'11','2','5586435');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('14',to_date('20/07/18','DD/MM/RR'),'6','2','5845793');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('15',to_date('20/07/18','DD/MM/RR'),'9','2','7583193');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('16',to_date('20/07/18','DD/MM/RR'),'3','2','7901645');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('17',to_date('20/07/18','DD/MM/RR'),'7','3','8299751');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('18',to_date('20/07/18','DD/MM/RR'),'5','3','8676153');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('19',to_date('20/07/18','DD/MM/RR'),'11','3','8801699');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('20',to_date('20/07/18','DD/MM/RR'),'8','3','9002811');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('21',to_date('20/07/18','DD/MM/RR'),'3','3','9539267');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('22',to_date('20/07/18','DD/MM/RR'),'10','3','9679940');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('23',to_date('20/07/18','DD/MM/RR'),'9','3','10038488');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('24',to_date('20/07/18','DD/MM/RR'),'1','3','11879295');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('25',to_date('20/07/18','DD/MM/RR'),'11','4','12141116');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('26',to_date('20/07/18','DD/MM/RR'),'10','4','12987266');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('27',to_date('20/07/18','DD/MM/RR'),'1','4','14051531');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('28',to_date('20/07/18','DD/MM/RR'),'9','4','15659921');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('29',to_date('20/07/18','DD/MM/RR'),'7','4','15905690');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('30',to_date('20/07/18','DD/MM/RR'),'3','4','17166549');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('31',to_date('20/07/18','DD/MM/RR'),'5','4','17255206');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('32',to_date('20/07/18','DD/MM/RR'),'8','4','17665094');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('33',to_date('20/07/18','DD/MM/RR'),'6','5','19612878');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('34',to_date('20/07/18','DD/MM/RR'),'8','5','19768693');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('35',to_date('20/07/18','DD/MM/RR'),'1','5','20254800');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('36',to_date('20/07/18','DD/MM/RR'),'9','5','20322516');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('37',to_date('20/07/18','DD/MM/RR'),'7','5','20500351');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('38',to_date('20/07/18','DD/MM/RR'),'11','5','21364643');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('39',to_date('20/07/18','DD/MM/RR'),'2','5','21898020');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('40',to_date('20/07/18','DD/MM/RR'),'10','5','22345651');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('41',to_date('20/07/18','DD/MM/RR'),'3','5','22968901');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('42',to_date('20/07/18','DD/MM/RR'),'9','6','23061531');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('43',to_date('20/07/18','DD/MM/RR'),'5','6','24472749');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('44',to_date('20/07/18','DD/MM/RR'),'6','6','24498120');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('45',to_date('20/07/18','DD/MM/RR'),'1','6','24809221');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('46',to_date('20/07/18','DD/MM/RR'),'7','6','25405449');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('47',to_date('20/07/18','DD/MM/RR'),'4','6','25536358');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('48',to_date('20/07/18','DD/MM/RR'),'11','6','27570413');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('49',to_date('20/07/18','DD/MM/RR'),'10','6','27961478');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('50',to_date('20/07/18','DD/MM/RR'),'3','6','28143035');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('51',to_date('20/07/18','DD/MM/RR'),'3','7','28297306');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('52',to_date('20/07/18','DD/MM/RR'),'5','7','29425171');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('53',to_date('20/07/18','DD/MM/RR'),'10','7','29585336');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('54',to_date('20/07/18','DD/MM/RR'),'8','7','29769217');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('55',to_date('20/07/18','DD/MM/RR'),'7','7','29965487');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('56',to_date('20/07/18','DD/MM/RR'),'6','7','30213987');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('57',to_date('20/07/18','DD/MM/RR'),'2','7','30817381');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('58',to_date('20/07/18','DD/MM/RR'),'1','7','31421030');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('59',to_date('20/07/18','DD/MM/RR'),'9','7','31588155');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('60',to_date('20/07/18','DD/MM/RR'),'3','8','33209034');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('61',to_date('20/07/18','DD/MM/RR'),'1','8','33266578');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('62',to_date('20/07/18','DD/MM/RR'),'5','8','34821345');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('63',to_date('20/07/18','DD/MM/RR'),'7','8','35098122');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('64',to_date('20/07/18','DD/MM/RR'),'11','8','37158020');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('65',to_date('20/07/18','DD/MM/RR'),'9','8','37196455');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('66',to_date('20/07/18','DD/MM/RR'),'6','8','37734232');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('67',to_date('20/07/18','DD/MM/RR'),'4','8','38370020');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('68',to_date('20/07/18','DD/MM/RR'),'8','8','38463171');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('69',to_date('20/07/18','DD/MM/RR'),'10','9','38647112');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('70',to_date('20/07/18','DD/MM/RR'),'1','9','39476444');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('71',to_date('20/07/18','DD/MM/RR'),'5','9','40928167');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('72',to_date('20/07/18','DD/MM/RR'),'7','9','41906482');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('73',to_date('20/07/18','DD/MM/RR'),'9','9','43047268');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('74',to_date('20/07/18','DD/MM/RR'),'2','9','44653774');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('75',to_date('20/07/18','DD/MM/RR'),'11','9','45427375');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('76',to_date('20/07/18','DD/MM/RR'),'8','9','45577349');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('77',to_date('20/07/18','DD/MM/RR'),'4','9','46944450');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('78',to_date('20/07/18','DD/MM/RR'),'10','10','47072543');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('79',to_date('20/07/18','DD/MM/RR'),'11','10','47221583');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('80',to_date('20/07/18','DD/MM/RR'),'1','10','47269316');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('81',to_date('20/07/18','DD/MM/RR'),'3','10','47551798');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('82',to_date('20/07/18','DD/MM/RR'),'9','10','49464632');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('83',to_date('20/07/18','DD/MM/RR'),'8','10','52024078');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('84',to_date('20/07/18','DD/MM/RR'),'5','10','52251926');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('85',to_date('20/07/18','DD/MM/RR'),'2','10','52307509');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('86',to_date('20/07/18','DD/MM/RR'),'6','10','52536075');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('87',to_date('20/07/18','DD/MM/RR'),'7','11','52592973');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('88',to_date('20/07/18','DD/MM/RR'),'8','11','52790811');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('89',to_date('20/07/18','DD/MM/RR'),'2','11','53074745');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('90',to_date('20/07/18','DD/MM/RR'),'1','11','53223034');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('91',to_date('20/07/18','DD/MM/RR'),'9','11','54036880');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('92',to_date('20/07/18','DD/MM/RR'),'7','11','54806654');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('93',to_date('20/07/18','DD/MM/RR'),'10','11','55007800');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('94',to_date('20/07/18','DD/MM/RR'),'3','11','56816611');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('95',to_date('20/07/18','DD/MM/RR'),'5','11','56848279');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('96',to_date('20/07/18','DD/MM/RR'),'5','12','57189858');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('97',to_date('20/07/18','DD/MM/RR'),'6','12','58232331');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('98',to_date('20/07/18','DD/MM/RR'),'8','12','58597347');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('99',to_date('20/07/18','DD/MM/RR'),'11','12','58950320');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('100',to_date('20/07/18','DD/MM/RR'),'7','12','59088863');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('101',to_date('20/07/18','DD/MM/RR'),'9','12','59166208');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('102',to_date('20/07/18','DD/MM/RR'),'3','12','60276134');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('103',to_date('20/07/18','DD/MM/RR'),'2','12','60647857');
Insert into JUGADOR_EQUIPO (ID_JUGADOR_EQUIPO,FECHA_INCORPORACION,CAMISETA,ID_EQUIPO,RUT_JUGADOR) values ('104',to_date('20/07/18','DD/MM/RR'),'1','12','60810081');
REM INSERTING into PARTIDO
SET DEFINE OFF;
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('1','1',to_timestamp('15/08/18 15:00:00,117854000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('15/08/18 16:59:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','1','3','4','1','2',to_date('15/08/18','DD/MM/RR'),'TELETUBBIES','CACHORROS','MILAN','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('2','2',to_timestamp('15/08/18 15:00:00,117854000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('15/08/18 16:59:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','0','1','2','3','3',to_date('15/08/18','DD/MM/RR'),'GRINGUITOS','PINGUINOS','MESSINA','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('3','3',to_timestamp('16/08/18 20:03:05,317341000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','5','6','2','5',to_date('16/08/18','DD/MM/RR'),'DEVASTADORES','DON JUAN FC','LIVORNO','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('4','4',to_timestamp('16/08/18 20:03:05,317341000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','8','7','1','8',to_date('16/08/18','DD/MM/RR'),'OLIMPIA','STOLICHVAYA','FLORENCIA','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('5','5',to_timestamp('17/08/18 16:00:00,285635000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('17/08/18 17:47:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'5','7','9','10','4','7',to_date('17/08/18','DD/MM/RR'),'LOGISTICA','BODEGA','TURIN','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('6','6',to_timestamp('17/08/18 16:00:00,285635000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('17/08/18 17:47:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'5','4','12','11','1','4',to_date('17/08/18','DD/MM/RR'),'INFORMATICA','CONTABILIDAD','ROMA','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('7','7',to_timestamp('18/08/18 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','4','3','4','1',to_date('18/08/18','DD/MM/RR'),'CACHORROS','TELETUBBIES','NAPOLES','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('8','8',to_timestamp('18/08/18 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','2','1','2','2',to_date('18/08/18','DD/MM/RR'),'PINGUINOS','GRINGUITOS','MILAN','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('9','9',to_timestamp('19/08/18 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('19/08/20 20:19:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'0','1','6','5','4','5',to_date('19/08/18','DD/MM/RR'),'DON JUAN FC','DEVASTADORES','LIVORNO','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('10','10',to_timestamp('19/08/18 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('19/08/20 20:19:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'0','1','7','8','3','4',to_date('19/08/18','DD/MM/RR'),'STOLICHVAYA','OLIMPIA','ROMA','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('11','11',to_timestamp('19/08/18 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('19/08/20 20:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'0','2','10','9','3','6',to_date('19/08/18','DD/MM/RR'),'BODEGA','LOGISTICA','VENECIA','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('12','12',to_timestamp('19/08/18 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','11','12','1','3',to_date('19/08/18','DD/MM/RR'),'CONTABILIDAD','INFORMATICA','MESSINA','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('13','13',to_timestamp('20/08/18 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','1','3','3','2',to_date('20/08/18','DD/MM/RR'),'GRINGUITOS','TELETUBBIES','MILAN','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('14','14',to_timestamp('20/08/18 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('20/08/20 20:00:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'7','5','4','1','3','5',to_date('20/08/18','DD/MM/RR'),'CACHORROS','GRINGUITOS','LIVORNO','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('15','15',to_timestamp('20/08/18 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('20/08/20 20:05:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','6','7','5','4','4',to_date('20/08/18','DD/MM/RR'),'STOLICHVAYA','DEVASTADORES','ROMA','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('16','16',to_timestamp('21/08/18 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('21/08/20 20:07:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','1','6','8','2','1',to_date('21/08/18','DD/MM/RR'),'DON JUAN FC','OLIMPIA','NAPOLES','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('17','17',to_timestamp('21/08/18 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('21/08/20 20:03:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'0','1','11','9','2','7',to_date('21/08/18','DD/MM/RR'),'CONTABILIDAD','LOGISTICA','TURIN','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('18','18',to_timestamp('22/08/18 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','10','12','1','8',to_date('22/08/18','DD/MM/RR'),'BODEGA','INFORMATICA','FLORENCIA','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('19','19',to_timestamp('23/08/18 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','10','3','2','8',to_date('23/08/18','DD/MM/RR'),'BODEGA','TELETUBBIES','FLORENCIA','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('20','20',to_timestamp('23/08/18 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('23/08/20 20:11:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','0','11','4','2','8',to_date('23/08/18','DD/MM/RR'),'CONTABILIDAD','CACHORROS','FLORENCIA','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('21','21',to_timestamp('23/08/18 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('23/08/20 20:16:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','1','8','5','1','5',to_date('23/08/18','DD/MM/RR'),'OLIMPIA','DEVASTADORES','LIVORNO','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('22','22',to_timestamp('24/08/18 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('24/08/20 20:18:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'0','0','6','2','4','4',to_date('24/08/18','DD/MM/RR'),'DON JUAN FC','PINGUINOS','ROMA','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('23','23',to_timestamp('24/08/18 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','12','9','3','1',to_date('24/08/18','DD/MM/RR'),'INFORMATICA','LOGISTICA','NAPOLES','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('24','24',to_timestamp('24/08/18 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','1','12','1','2',to_date('24/08/18','DD/MM/RR'),'GRINGUITOS','INFORMATICA','MILAN','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('25','25',to_timestamp('25/08/18 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','6','3','2','3',to_date('25/08/18','DD/MM/RR'),'DON JUAN FC','TELETUBBIES','MESSINA','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('26','26',to_timestamp('26/08/18 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('26/08/20 20:14:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'0','1','11','8','4','2',to_date('26/08/18','DD/MM/RR'),'CONTABILIDAD','OLIMPIA','MILAN','1');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('27','27',to_timestamp('27/08/18 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('27/08/20 20:05:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'0','1','10','5','1','1',to_date('27/08/18','DD/MM/RR'),'BODEGA','DEVASTADORES','NAPOLES','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('28','28',to_timestamp('28/08/18 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','6','1','2','5',to_date('28/08/18','DD/MM/RR'),'DON JUAN FC','GRINGUITOS','LIVORNO','3');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('29','29',to_timestamp('28/08/18 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),null,'0','0','12','4','1','5',to_date('28/08/18','DD/MM/RR'),'INFORMATICA','CACHORROS','LIVORNO','2');
Insert into PARTIDO (ID_PARTIDO,ID_PROGRAMACION,INICIO,FIN,GOLES_LOCAL,GOLES_VISITA,ID_EQUIPO_LOCAL,ID_EQUIPO_VISITA,ID_USER,ID_CANCHA,FECHA,EQUIPO_LOCAL,EQUIPO_VISITA,CANCHA,ID_TARIFA) values ('30','30',to_timestamp('29/08/18 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/08/20 20:08:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'0','0','9','12','3','4',to_date('29/08/18','DD/MM/RR'),'LOGISTICA','INFORMATICA','ROMA','2');
REM INSERTING into PROGRAMACION
SET DEFINE OFF;
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('1','3','4',to_date('15/08/18','DD/MM/RR'),to_timestamp('15/08/18 15:00:00,117854000','DD/MM/RR HH24:MI:SSXFF'),'1','20000','J ','TELETUBBIES','CACHORROS','119');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('2','1','2',to_date('15/08/18','DD/MM/RR'),to_timestamp('15/08/18 15:00:00,117854000','DD/MM/RR HH24:MI:SSXFF'),'1','20000','J ','GRINGUITOS','PINGUINOS','119');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('3','5','6',to_date('16/08/18','DD/MM/RR'),to_timestamp('16/08/18 20:03:05,317341000','DD/MM/RR HH24:MI:SSXFF'),'3','25000','NJ','DEVASTADORES','DON JUAN FC',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('4','8','7',to_date('16/08/18','DD/MM/RR'),to_timestamp('16/08/18 20:03:05,317341000','DD/MM/RR HH24:MI:SSXFF'),'3','30000','NJ','OLIMPIA','STOLICHVAYA',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('5','9','10',to_date('17/08/18','DD/MM/RR'),to_timestamp('17/08/18 16:00:00,285635000','DD/MM/RR HH24:MI:SSXFF'),'2','40000','J ','LOGISTICA','BODEGA','107');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('6','12','11',to_date('17/08/18','DD/MM/RR'),to_timestamp('17/08/18 16:00:00,285635000','DD/MM/RR HH24:MI:SSXFF'),'2','40000','J ','INFORMATICA','CONTABILIDAD','107');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('7','4','3',to_date('18/08/18','DD/MM/RR'),to_timestamp('18/08/20 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','15000','NJ','CACHORROS','TELETUBBIES',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('8','2','1',to_date('18/08/18','DD/MM/RR'),to_timestamp('18/08/20 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','10000','NJ','PINGUINOS','GRINGUITOS',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('9','6','5',to_date('19/08/18','DD/MM/RR'),to_timestamp('19/08/20 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','50000','J ','DON JUAN FC','DEVASTADORES','120');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('10','7','8',to_date('19/08/18','DD/MM/RR'),to_timestamp('19/08/20 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','50000','J ','STOLICHVAYA','OLIMPIA','120');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('11','10','9',to_date('19/08/18','DD/MM/RR'),to_timestamp('19/08/20 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','40000','J ','BODEGA','LOGISTICA','120');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('12','11','12',to_date('19/08/18','DD/MM/RR'),to_timestamp('19/08/20 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','20000','NJ','CONTABILIDAD','INFORMATICA',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('13','1','3',to_date('20/08/18','DD/MM/RR'),to_timestamp('20/08/20 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','10000','NJ','GRINGUITOS','TELETUBBIES',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('14','4','1',to_date('20/08/18','DD/MM/RR'),to_timestamp('20/08/20 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','35000','J ','CACHORROS','GRINGUITOS','106');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('15','7','5',to_date('20/08/18','DD/MM/RR'),to_timestamp('20/08/20 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','50000','J ','STOLICHVAYA','DEVASTADORES','106');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('16','6','8',to_date('21/08/18','DD/MM/RR'),to_timestamp('21/08/20 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','50000','J ','DON JUAN FC','OLIMPIA','108');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('17','11','9',to_date('21/08/18','DD/MM/RR'),to_timestamp('21/08/20 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','40000','J ','CONTABILIDAD','LOGISTICA','108');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('18','10','12',to_date('22/08/18','DD/MM/RR'),to_timestamp('22/08/20 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','5000','NJ','BODEGA','INFORMATICA',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('19','10','3',to_date('23/08/18','DD/MM/RR'),to_timestamp('23/08/20 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','15000','NJ','BODEGA','TELETUBBIES',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('20','11','4',to_date('23/08/18','DD/MM/RR'),to_timestamp('23/08/20 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','15000','J ','CONTABILIDAD','CACHORROS','117');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('21','8','5',to_date('23/08/18','DD/MM/RR'),to_timestamp('23/08/20 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','50000','J ','OLIMPIA','DEVASTADORES','117');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('22','6','2',to_date('24/08/18','DD/MM/RR'),to_timestamp('24/08/20 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','40000','J ','DON JUAN FC','PINGUINOS','119');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('23','12','9',to_date('24/08/18','DD/MM/RR'),to_timestamp('24/08/20 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','8000','NJ','INFORMATICA','LOGISTICA',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('24','1','12',to_date('24/08/18','DD/MM/RR'),to_timestamp('24/08/20 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','10000','NJ','GRINGUITOS','INFORMATICA',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('25','6','3',to_date('25/08/18','DD/MM/RR'),to_timestamp('25/08/20 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','20000','NJ','DON JUAN FC','TELETUBBIES',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('26','11','8',to_date('26/08/18','DD/MM/RR'),to_timestamp('26/08/20 18:15:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','35000','J ','CONTABILIDAD','OLIMPIA','120');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('27','10','5',to_date('27/08/18','DD/MM/RR'),to_timestamp('27/08/20 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','50000','J ','BODEGA','DEVASTADORES','106');
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('28','6','1',to_date('28/08/18','DD/MM/RR'),to_timestamp('28/08/20 18:20:03,000000000','DD/MM/RR HH24:MI:SSXFF'),'3','25000','NJ','DON JUAN FC','GRINGUITOS',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('29','12','4',to_date('28/08/18','DD/MM/RR'),to_timestamp('28/08/20 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','40000','NJ','INFORMATICA','CACHORROS',null);
Insert into PROGRAMACION (ID_PROGRAMACION,ID_EQUIPO_1,ID_EQUIPO_2,FECHA,HORA,ID_TARIFA,VALOR_PAGADO,ESTADO,EQUIPO_1,EQUIPO_2,MINUTOS_JUGADOS) values ('30','9','12',to_date('29/08/18','DD/MM/RR'),to_timestamp('29/08/20 18:16:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'2','40000','J ','LOGISTICA','INFORMATICA','113');
REM INSERTING into TARIFA
SET DEFINE OFF;
Insert into TARIFA (ID_TARIFA,DESCRIPCION,VALOR,FECHA_CREACION,FECHA_ACTUALIZACION,FECHA_ELIMINACION,ID_USER_CREACION,ID_USER_ACTUALIZACION,ID_USER_ELIMINACION) values ('1','LOW','35000',to_date('01/08/18','DD/MM/RR'),null,null,'1',null,null);
Insert into TARIFA (ID_TARIFA,DESCRIPCION,VALOR,FECHA_CREACION,FECHA_ACTUALIZACION,FECHA_ELIMINACION,ID_USER_CREACION,ID_USER_ACTUALIZACION,ID_USER_ELIMINACION) values ('2','MEDIUM','40000',to_date('01/08/18','DD/MM/RR'),null,null,'1',null,null);
Insert into TARIFA (ID_TARIFA,DESCRIPCION,VALOR,FECHA_CREACION,FECHA_ACTUALIZACION,FECHA_ELIMINACION,ID_USER_CREACION,ID_USER_ACTUALIZACION,ID_USER_ELIMINACION) values ('3','HIGH','50000',to_date('01/08/18','DD/MM/RR'),null,null,'1',null,null);
REM INSERTING into TIPO_EVENTO
SET DEFINE OFF;
Insert into TIPO_EVENTO (DESCRIPCION,RELEVANTE,ID_TIPO_EVENTO) values ('GOL','Y','GL');
Insert into TIPO_EVENTO (DESCRIPCION,RELEVANTE,ID_TIPO_EVENTO) values ('FOUL','Y','FO');
Insert into TIPO_EVENTO (DESCRIPCION,RELEVANTE,ID_TIPO_EVENTO) values ('OFF SIDE','N','OF');
Insert into TIPO_EVENTO (DESCRIPCION,RELEVANTE,ID_TIPO_EVENTO) values ('LATERAL','N','LA');
Insert into TIPO_EVENTO (DESCRIPCION,RELEVANTE,ID_TIPO_EVENTO) values ('EXPULSION','Y','EX');
Insert into TIPO_EVENTO (DESCRIPCION,RELEVANTE,ID_TIPO_EVENTO) values ('AMONESTACION','Y','AM');
REM INSERTING into USUARIO
SET DEFINE OFF;
Insert into USUARIO (ID_USER,USERNAME,PASSWORD,FECHA_CREACION,FECHA_BLOQUEO,NOMBRE,APELLIDO) values ('1','JVALENZUELA','1',to_date('13/11/17','DD/MM/RR'),null,'JUAN','VALENZUELA');
Insert into USUARIO (ID_USER,USERNAME,PASSWORD,FECHA_CREACION,FECHA_BLOQUEO,NOMBRE,APELLIDO) values ('2','MCLARO','1',to_date('13/11/17','DD/MM/RR'),null,'MIGUEL','CLARO');
Insert into USUARIO (ID_USER,USERNAME,PASSWORD,FECHA_CREACION,FECHA_BLOQUEO,NOMBRE,APELLIDO) values ('4','PLORCA','1',to_date('25/07/18','DD/MM/RR'),null,'PABLO','LORCA');
Insert into USUARIO (ID_USER,USERNAME,PASSWORD,FECHA_CREACION,FECHA_BLOQUEO,NOMBRE,APELLIDO) values ('3','CURBINA','1',to_date('22/08/18','DD/MM/RR'),null,'CAROL','URBINA');
--------------------------------------------------------
--  DDL for Index CANCHA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANCHA_PK" ON "CANCHA" ("ID_CANCHA") ;
--------------------------------------------------------
--  DDL for Index PARTIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTIDO_PK" ON "PARTIDO" ("ID_PARTIDO") ;
--------------------------------------------------------
--  DDL for Index EVENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVENTO_PK" ON "EVENTO" ("ID_EVENTO") ;
--------------------------------------------------------
--  DDL for Index TIPO_EVENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPO_EVENTO_PK" ON "TIPO_EVENTO" ("ID_TIPO_EVENTO") ;
--------------------------------------------------------
--  DDL for Index JUGADOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUGADOR_PK" ON "JUGADOR" ("RUT") ;
--------------------------------------------------------
--  DDL for Index TARIFA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TARIFA_PK" ON "TARIFA" ("ID_TARIFA") ;
--------------------------------------------------------
--  DDL for Index JUGADOR_EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUGADOR_EQUIPO_PK" ON "JUGADOR_EQUIPO" ("ID_JUGADOR_EQUIPO") ;
--------------------------------------------------------
--  DDL for Index PROGRAMACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION_PK" ON "PROGRAMACION" ("ID_PROGRAMACION") ;
--------------------------------------------------------
--  DDL for Index EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EQUIPO_PK" ON "EQUIPO" ("ID_EQUIPO") ;
--------------------------------------------------------
--  DDL for Index CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CATEGORIA_PK" ON "CATEGORIA" ("ID_CATEGORIA") ;
--------------------------------------------------------
--  Constraints for Table JUGADOR_EQUIPO
--------------------------------------------------------

  ALTER TABLE "JUGADOR_EQUIPO" ADD CONSTRAINT "JUGADOR_EQUIPO_PK" PRIMARY KEY ("ID_JUGADOR_EQUIPO") ENABLE;
  ALTER TABLE "JUGADOR_EQUIPO" MODIFY ("RUT_JUGADOR" NOT NULL ENABLE);
  ALTER TABLE "JUGADOR_EQUIPO" MODIFY ("ID_EQUIPO" NOT NULL ENABLE);
  ALTER TABLE "JUGADOR_EQUIPO" MODIFY ("CAMISETA" NOT NULL ENABLE);
  ALTER TABLE "JUGADOR_EQUIPO" MODIFY ("FECHA_INCORPORACION" NOT NULL ENABLE);
  ALTER TABLE "JUGADOR_EQUIPO" MODIFY ("ID_JUGADOR_EQUIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TARIFA
--------------------------------------------------------

  ALTER TABLE "TARIFA" ADD CONSTRAINT "TARIFA_PK" PRIMARY KEY ("ID_TARIFA") ENABLE;
  ALTER TABLE "TARIFA" MODIFY ("ID_USER_CREACION" NOT NULL ENABLE);
  ALTER TABLE "TARIFA" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "TARIFA" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "TARIFA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TARIFA" MODIFY ("ID_TARIFA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "USUARIO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "USUARIO" ADD PRIMARY KEY ("ID_USER") ENABLE;
  ALTER TABLE "USUARIO" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTO
--------------------------------------------------------

  ALTER TABLE "EVENTO" ADD CONSTRAINT "EVENTO_PK" PRIMARY KEY ("ID_EVENTO") ENABLE;
  ALTER TABLE "EVENTO" MODIFY ("MINUTO" NOT NULL ENABLE);
  ALTER TABLE "EVENTO" MODIFY ("ID_PARTIDO" NOT NULL ENABLE);
  ALTER TABLE "EVENTO" MODIFY ("ID_EVENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_EVENTO
--------------------------------------------------------

  ALTER TABLE "TIPO_EVENTO" MODIFY ("RELEVANTE" NOT NULL ENABLE);
  ALTER TABLE "TIPO_EVENTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TIPO_EVENTO" ADD CONSTRAINT "TIPO_EVENTO_PK" PRIMARY KEY ("ID_TIPO_EVENTO") ENABLE;
  ALTER TABLE "TIPO_EVENTO" MODIFY ("ID_TIPO_EVENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "EQUIPO" ADD CONSTRAINT "EQUIPO_PK" PRIMARY KEY ("ID_EQUIPO") ENABLE;
  ALTER TABLE "EQUIPO" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "EQUIPO" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "EQUIPO" MODIFY ("CANTIDAD_JUGADOR" NOT NULL ENABLE);
  ALTER TABLE "EQUIPO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "EQUIPO" MODIFY ("ID_EQUIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTIDO
--------------------------------------------------------

  ALTER TABLE "PARTIDO" MODIFY ("EQUIPO_VISITA" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("ID_TARIFA" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" ADD CONSTRAINT "PARTIDO_PK" PRIMARY KEY ("ID_PARTIDO") ENABLE;
  ALTER TABLE "PARTIDO" MODIFY ("ID_EQUIPO_VISITA" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("ID_EQUIPO_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("GOLES_VISITA" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("GOLES_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("EQUIPO_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("ID_CANCHA" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("INICIO" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("ID_PROGRAMACION" NOT NULL ENABLE);
  ALTER TABLE "PARTIDO" MODIFY ("ID_PARTIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANCHA
--------------------------------------------------------

  ALTER TABLE "CANCHA" ADD CONSTRAINT "CANCHA_PK" PRIMARY KEY ("ID_CANCHA") ENABLE;
  ALTER TABLE "CANCHA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CANCHA" MODIFY ("ID_CANCHA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "CATEGORIA" ADD CONSTRAINT "CATEGORIA_PK" PRIMARY KEY ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "CATEGORIA" MODIFY ("EDAD_MAXIMO" NOT NULL ENABLE);
  ALTER TABLE "CATEGORIA" MODIFY ("EDAD_MINIMA" NOT NULL ENABLE);
  ALTER TABLE "CATEGORIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROGRAMACION
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION" ADD CONSTRAINT "PROGRAMACION_PK" PRIMARY KEY ("ID_PROGRAMACION") ENABLE;
  ALTER TABLE "PROGRAMACION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PROGRAMACION" MODIFY ("VALOR_PAGADO" NOT NULL ENABLE);
  ALTER TABLE "PROGRAMACION" MODIFY ("ID_TARIFA" NOT NULL ENABLE);
  ALTER TABLE "PROGRAMACION" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "PROGRAMACION" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "PROGRAMACION" MODIFY ("ID_EQUIPO_2" NOT NULL ENABLE);
  ALTER TABLE "PROGRAMACION" MODIFY ("ID_EQUIPO_1" NOT NULL ENABLE);
  ALTER TABLE "PROGRAMACION" MODIFY ("ID_PROGRAMACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JUGADOR
--------------------------------------------------------

  ALTER TABLE "JUGADOR" ADD CONSTRAINT "JUGADOR_PK" PRIMARY KEY ("RUT") ENABLE;
  ALTER TABLE "JUGADOR" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "JUGADOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "JUGADOR" MODIFY ("DV" NOT NULL ENABLE);
  ALTER TABLE "JUGADOR" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "EQUIPO" ADD CONSTRAINT "EQUIPO_CATEGORIA_FK" FOREIGN KEY ("ID_CATEGORIA") REFERENCES "CATEGORIA" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTO
--------------------------------------------------------

  ALTER TABLE "EVENTO" ADD CONSTRAINT "EVENTO_JUGADOR_FK" FOREIGN KEY ("RUT_JUGADOR") REFERENCES "JUGADOR" ("RUT") ENABLE;
  ALTER TABLE "EVENTO" ADD CONSTRAINT "EVENTO_TIPO_EVENTO_FK" FOREIGN KEY ("ID_TIPO_EVENTO") REFERENCES "TIPO_EVENTO" ("ID_TIPO_EVENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGADOR_EQUIPO
--------------------------------------------------------

  ALTER TABLE "JUGADOR_EQUIPO" ADD CONSTRAINT "JUGADOR_EQUIPO_EQUIPO_FK" FOREIGN KEY ("ID_EQUIPO") REFERENCES "EQUIPO" ("ID_EQUIPO") ENABLE;
  ALTER TABLE "JUGADOR_EQUIPO" ADD CONSTRAINT "JUGADOR_EQUIPO_JUGADOR_FK" FOREIGN KEY ("RUT_JUGADOR") REFERENCES "JUGADOR" ("RUT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTIDO
--------------------------------------------------------

  ALTER TABLE "PARTIDO" ADD CONSTRAINT "PARTIDO_CANCHA_FK" FOREIGN KEY ("ID_CANCHA") REFERENCES "CANCHA" ("ID_CANCHA") ENABLE;
  ALTER TABLE "PARTIDO" ADD CONSTRAINT "PARTIDO_EQUIPO_FK" FOREIGN KEY ("ID_EQUIPO_LOCAL") REFERENCES "EQUIPO" ("ID_EQUIPO") ENABLE;
  ALTER TABLE "PARTIDO" ADD CONSTRAINT "PARTIDO_EQUIPO_FKV1" FOREIGN KEY ("ID_EQUIPO_VISITA") REFERENCES "EQUIPO" ("ID_EQUIPO") ENABLE;
  ALTER TABLE "PARTIDO" ADD CONSTRAINT "PARTIDO_PROGRAMACION_FK" FOREIGN KEY ("ID_PARTIDO") REFERENCES "PARTIDO" ("ID_PARTIDO") ENABLE;
  ALTER TABLE "PARTIDO" ADD CONSTRAINT "PARTIDO_USUARIO_FK" FOREIGN KEY ("ID_USER") REFERENCES "USUARIO" ("ID_USER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROGRAMACION
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION" ADD CONSTRAINT "PROGRAMACION_EQUIPO_2_FK" FOREIGN KEY ("ID_EQUIPO_2") REFERENCES "EQUIPO" ("ID_EQUIPO") ENABLE;
  ALTER TABLE "PROGRAMACION" ADD CONSTRAINT "PROGRAMACION_TARIFA_FK" FOREIGN KEY ("ID_TARIFA") REFERENCES "TARIFA" ("ID_TARIFA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TARIFA
--------------------------------------------------------

  ALTER TABLE "TARIFA" ADD CONSTRAINT "TARIFA_USUARIO_CREA_FK" FOREIGN KEY ("ID_USER_ELIMINACION") REFERENCES "USUARIO" ("ID_USER") ENABLE;
